[package]
name = "sumdir"
version = "0.2.0"
authors = ["Sharaf Zaman <sharafzaz121@gmail.com>"]
edition = "2018"
description = "Compute deterministic hash of a directory"
license = "MIT"

[dependencies]
blake2 = "0.8.0"
walkdir = "2"
base64 = "0.10"
